[package]
name = "snow"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kiss3d = "0.32"
nalgebra = "0.29"
rand = "0.8.4"
statrs = "0.15"